																				
Pattern of alphabets consisting of 5 rows:                                      
A                                                                               
A B                                                                             
A B C                                                                           
A B C D                                                                         
A B C D E                                                                       
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
                                                                                
